apiVersion: v1 
kind: Service 
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1 
kind: Service 
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    component: mysql
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      component: mysql # has to match .spec.template.metadata.labels
      project: expense
      tier: db
  serviceName: "mysql-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mysql # has to match .spec.selector.matchLabels
        project: expense
        tier: db
    spec:
      containers:
      - name: mysql
        image: saikumar718/mysqlv1.0.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1G      
